name: Build firmware
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc build-essential gcc-xtensa-lx106

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal

      - name: Install espup
        run: |
          cargo install espup

      - name: Install esp32 toolchain
        run: |
          espup install -t esp32 --toolchain-version 1.76.0.0

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: elbike-power-meter.elf
          path: target/xtensa-esp8266-none-elf/release/elbike-power-meter
          if-no-files-found: error
